### PR TITLE
Fix/unity latency and add freelook

### PR DESCRIPTION
**Pull request by alamarre3**
## Description
Fixed poor performance and responsiveness of the build simulation. Also improve the fly cam.

## Fixes
- Remove the wait function in the update() method of ros img publisher. Causing bad performance.
- Use FixedUpdate() instead of Update() as it use the backend clock instead of the refresh rate for ros msg.
- Fly cam is now 3rd person like using cinemachine https://www.youtube.com/watch?v=sLMrbB2-smw&ab_channel=OmarBalfaqih
- Added input command for Fly cam : left click + mouse for cam rotation and mouse scroll for zoom

## How has this been tested ?
tested locally
## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by kaowilly — COMMENTED** [review]
Front and bottom cameras are shown correctly in the telemetry, but the front cam isn't rendered properly in "Display 3" view in Unity.

**Comment by alamarre3** [comment]
front cam as been fixed in disp 3

**Comment by kaowilly** [comment]
To toggle between the FlyCam and FreeCam:
Key 1: FreeCam
Key 4: FlyCam

**Review by Kam0ss — APPROVED** [review]
LGTM

**Pull request merged**
